# Generated by Django 5.1.4 on 2024-12-17 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_alter_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='mechanic',
            name='profile_pic',
        ),
    ]
